<?php
$page_title = '服务器状态 - LuckyClover';
$page_desc = '查看 LuckyClover 服务器状态，了解在线人数、版本、游戏模式与运行情况。';
$active_nav = 'status';
require __DIR__ . '/includes/bootstrap.php';
$servers = $db->query('SELECT slug, name, type, host, port FROM servers WHERE enabled = 1 ORDER BY sort_order ASC, id ASC')->fetchAll();
$extra_css = <<<'CSS'
.status-card{background:var(--bg-card);border:1px solid var(--border-color);border-radius:var(--radius-lg);padding:48px;text-align:center;max-width:760px;margin:0 auto}.status-server-ip{font-size:1.5rem;font-weight:600;margin:16px 0;padding:16px;background:var(--bg-secondary);border-radius:var(--radius-md)}.status-badge{display:inline-flex;align-items:center;gap:8px;padding:8px 16px;background:rgba(0,210,106,.1);color:#00d26a;border-radius:50px;font-weight:500}.status-badge .dot{width:8px;height:8px;background:#00d26a;border-radius:50%;animation:pulse 2s ease-in-out infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}.page-header{text-align:center;padding:120px 24px 60px}.page-header h1{font-size:3rem;margin-bottom:16px}.status-offline{background:rgba(244,67,54,.1);color:#f44336}.status-details{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:24px}.status-detail{background:var(--bg-secondary);padding:16px;border-radius:var(--radius-md)}.status-detail .label{font-size:.75rem;color:var(--text-muted);margin-bottom:4px}.status-detail .value{font-size:1rem;font-weight:500}@media(max-width:600px){.status-details{grid-template-columns:1fr}}
CSS;
require __DIR__ . '/includes/header.php';
?>
<section class="page-header"><div class="container"><h1>服务器<span style="color:var(--accent-secondary);">状态</span></h1><p>实时查看 LuckyClover 运行情况</p></div></section>
<section class="section"><div class="container">
<?php if (!$servers): ?><div class="status-card"><p>暂无启用的服务器。</p></div><?php endif; ?>
<?php foreach ($servers as $server): ?><div class="status-card" style="margin-top:32px" data-server-host="<?php echo e($server['host']); ?>" data-server-port="<?php echo (int) $server['port']; ?>"><div class="status-badge" data-status-badge><span class="dot"></span><span data-status-text>检测中...</span></div><div class="status-server-ip"><?php echo e($server['name']); ?></div><p style="color:var(--text-secondary)"><?php echo e($server['type']); ?></p><div class="status-details"><div class="status-detail"><div class="label">在线玩家</div><div class="value" data-players>--</div></div><div class="status-detail"><div class="label">游戏版本</div><div class="value" data-version>--</div></div><div class="status-detail"><div class="label">游戏模式</div><div class="value" data-gamemode>--</div></div></div><div class="status-details" style="margin-top:16px;grid-template-columns:1fr"><div class="status-detail"><div class="label">MOTD</div><div class="value" data-motd style="font-size:.875rem">--</div></div></div></div><?php endforeach; ?>
</div></section>
<?php $extra_js = <<<'JS'
async function updateServerStatuses(){document.querySelectorAll('[data-server-host]').forEach(async card=>{try{const response=await fetch(`https://motd.minebbs.com/api/status?ip=${encodeURIComponent(card.dataset.serverHost)}&port=${card.dataset.serverPort}&stype=auto&_=${Date.now()}`,{cache:'no-store'});const data=await response.json();const online=data.status==='online';card.querySelector('[data-status-badge]').className=online?'status-badge':'status-badge status-offline';card.querySelector('[data-status-text]').textContent=online?'在线':'离线';card.querySelector('[data-players]').textContent=online&&data.players?`${data.players.online}/${data.players.max}`:'0';card.querySelector('[data-version]').textContent=online?(data.version||'--'):'--';card.querySelector('[data-gamemode]').textContent=online?(data.gamemode||'生存'):'--';card.querySelector('[data-motd]').textContent=online?(data.motd||'-'):'服务器离线'}catch(error){card.querySelector('[data-status-badge]').className='status-badge status-offline';card.querySelector('[data-status-text]').textContent='查询失败'}})}setInterval(updateServerStatuses,30000);updateServerStatuses();
JS; require __DIR__ . '/includes/footer.php'; ?>
